using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;


public class Example : MonoBehaviour{
    private bool WWalkingFlag = false;

    private bool AWalkingFlag = false;

    private bool SWalkingFlag = false;

    private bool DWalkingFlag = false;

    private bool movementFlag = false;

    private bool sprintingFlag = false;

    public float standingsound = 1.5f;
    public float walkingSound = 5.0f;
    private float sizeChange = 1.6f;
    void Start(){

    }
 
 //forgive me for what im about to do. Im about to make code so bad the lord's eyes might bleed. Amen.
    void Update(){
       
                //Enlarges "Sound radius" When walking 
        if (Input.GetKeyDown(KeyCode.W)){
            WWalkingFlag = true;
        } else if(Input.GetKeyDown(KeyCode.A)){
            AWalkingFlag = true;
        } else if(Input.GetKeyDown(KeyCode.S)){
            SWalkingFlag = true;
        } else if(Input.GetKeyDown(KeyCode.D)){
            DWalkingFlag = true;
        }

         if (Input.GetKeyUp(KeyCode.W)){
            WWalkingFlag = false;
        } else if(Input.GetKeyUp(KeyCode.A)){
            AWalkingFlag = false;
        } else if(Input.GetKeyUp(KeyCode.S)){
            SWalkingFlag = false;
        } else if(Input.GetKeyUp(KeyCode.D)){
            DWalkingFlag = false;
        }
        
        if (WWalkingFlag || AWalkingFlag || SWalkingFlag || DWalkingFlag){
            movementFlag = true;
            transform.localScale = new Vector3(sizeChange + 4.0f, sizeChange + 4.0f, sizeChange + 4.0f);
                  }
                //Turns it back to Normal (No sound generated by player)
        if (!WWalkingFlag && !AWalkingFlag && !SWalkingFlag && !DWalkingFlag){
            movementFlag = false;
            transform.localScale = new Vector3(sizeChange, sizeChange, sizeChange);
            }

            //Sprinting sound generation
        if (Input.GetKeyDown(KeyCode.LeftShift)){
            sprintingFlag = true;
                  }
        if (Input.GetKeyUp(KeyCode.LeftShift)){
            sprintingFlag = false;
        }

        if(sprintingFlag && movementFlag){
            transform.localScale = new Vector3(sizeChange + 10.0f, sizeChange + 10.0f, sizeChange + 10.0f);
        } else if (!sprintingFlag && movementFlag){
            new Vector3(sizeChange + 4.0f, sizeChange + 4.0f, sizeChange + 4.0f);
        } else if (!sprintingFlag && !movementFlag){
           transform.localScale = new Vector3(sizeChange, sizeChange, sizeChange); 
        }
    }




}

