using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;


public class Example : MonoBehaviour{
    private bool forwardWalkingFlag = false;
    public float standingsound = 1.5f;
    public float walkingSound = 5.0f;
    private float sizeChange = 1.6f;
    void Start(){

    }
 
 //forgive me for what im about to do. Im about to make code so bad the lord's eyes might bleed. Amen.
    void Update(){
       
                //Enlarges "Sound radius" When walking 
        if (Input.GetKeyDown(KeyCode.W) || Input.GetKeyDown(KeyCode.A) || Input.GetKeyDown(KeyCode.S) || Input.GetKeyDown(KeyCode.D)){
            forwardWalkingFlag = 1.0f;

            transform.localScale = new Vector3(sizeChange + 4.0f, sizeChange + 4.0f, sizeChange + 4.0f);
                  }
                //Turns it back to Normal (No sound generated by player)
        if (Input.GetKeyUp(KeyCode.W)|| Input.GetKeyUp(KeyCode.A) || Input.GetKeyUp(KeyCode.S) || Input.GetKeyUp(KeyCode.D)){
             walkingFlag = -1.0f;
            transform.localScale = new Vector3(sizeChange, sizeChange, sizeChange);
        
            }

            //Sprinting sound generation
        if (Input.GetKeyDown(KeyCode.LeftShift) && walkingFlag == 1.0f){

            transform.localScale = new Vector3(sizeChange + 10.0f, sizeChange + 10.0f, sizeChange + 10.0f);
                  }
        if (Input.GetKeyUp(KeyCode.LeftShift) && walkingFlag == 1.0f){
            transform.localScale = new Vector3(sizeChange + 4.0f, sizeChange + 4.0f, sizeChange + 4.0f);

        }
        if(Input.GetKeyUp(KeyCode.LeftShift)){
            transform.localScale = new Vector3(sizeChange, sizeChange, sizeChange);
        }
    }
}

