using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class Example : MonoBehaviour{

    public float standingsound = 1.5f;
    public float walkingSound = 5.0f;
    void Start(){

    }

 //forgive me for what im about to do. Im about to make code so bad the lord's eyes might bleed. Amen.
    void Update(){
       
                //Enlarges "Sound radius" When walking 
        if (Input.GetKeyDown(KeyCode.W)){

            transform.localScale = new Vector3(5.0f, 5.0f, 5.0f);
                  }
                //Turns it back to Normal (No sound generated by player)
        if (Input.GetKeyUp(KeyCode.W)){
            transform.localScale = new Vector3(1.6f, 1.6f, 1.6f);
        
            }
        if (Input.GetKeyDown(KeyCode.LeftShift)){

            transform.localScale = new Vector3(10.0f, 10.0f, 10.0f);
                  }
        if (Input.GetKeyUp(KeyCode.LeftShift)){
            transform.localScale = new Vector3(1.6f, 1.6f, 1.6f);

        }
    }
}

